// Datos de muestra para el dashboard de carriles preferenciales
window.SAMPLE_DATA = [
    // Av. Boyacá - NS - Diciembre 2021
    {
        fecha: "2021-12-15",
        hora: "00:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 0
    },
    {
        fecha: "2021-12-15",
        hora: "01:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 0
    },
    {
        fecha: "2021-12-15",
        hora: "06:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 15
    },
    {
        fecha: "2021-12-15",
        hora: "07:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 45
    },
    {
        fecha: "2021-12-15",
        hora: "08:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 78
    },
    {
        fecha: "2021-12-15",
        hora: "09:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 65
    },
    {
        fecha: "2021-12-15",
        hora: "17:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 89
    },
    {
        fecha: "2021-12-15",
        hora: "18:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 92
    },
    {
        fecha: "2021-12-15",
        hora: "19:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 67
    },
    {
        fecha: "2021-12-15",
        hora: "20:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 34
    },
    {
        fecha: "2021-12-15",
        hora: "21:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 12
    },
    {
        fecha: "2021-12-15",
        hora: "22:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 8
    },
    {
        fecha: "2021-12-15",
        hora: "23:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 3
    },

    // Av. Boyacá - NS - Diciembre 2021 - Viernes
    {
        fecha: "2021-12-17",
        hora: "08:00:00",
        semana: "50",
        dia: "Viernes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 82
    },
    {
        fecha: "2021-12-17",
        hora: "17:00:00",
        semana: "50",
        dia: "Viernes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 95
    },

    // Av. Boyacá - NS - Diciembre 2021 - Sábado
    {
        fecha: "2021-12-18",
        hora: "10:00:00",
        semana: "50",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Sábado",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 45
    },
    {
        fecha: "2021-12-18",
        hora: "14:00:00",
        semana: "50",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Sábado",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 38
    },

    // Av. Boyacá - NS - Diciembre 2021 - Domingo
    {
        fecha: "2021-12-19",
        hora: "12:00:00",
        semana: "51",
        dia: "Domingo",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 25
    },
    {
        fecha: "2021-12-19",
        hora: "16:00:00",
        semana: "51",
        dia: "Domingo",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 32
    },

    // Av. Kr. 13 - EW - Diciembre 2021
    {
        fecha: "2021-12-15",
        hora: "07:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Kr. 13",
        sentido: "EW",
        desde: "Av. Cl. 26",
        hasta: "Av. Cl. 100",
        congestion: 52
    },
    {
        fecha: "2021-12-15",
        hora: "08:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Kr. 13",
        sentido: "EW",
        desde: "Av. Cl. 26",
        hasta: "Av. Cl. 100",
        congestion: 88
    },
    {
        fecha: "2021-12-15",
        hora: "17:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Kr. 13",
        sentido: "EW",
        desde: "Av. Cl. 26",
        hasta: "Av. Cl. 100",
        congestion: 91
    },
    {
        fecha: "2021-12-15",
        hora: "18:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Kr. 13",
        sentido: "EW",
        desde: "Av. Cl. 26",
        hasta: "Av. Cl. 100",
        congestion: 76
    },

    // Av. Kr. 13 - EW - Diciembre 2021 - Sábado
    {
        fecha: "2021-12-18",
        hora: "11:00:00",
        semana: "50",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Sábado",
        carril: "Av. Kr. 13",
        sentido: "EW",
        desde: "Av. Cl. 26",
        hasta: "Av. Cl. 100",
        congestion: 42
    },
    {
        fecha: "2021-12-18",
        hora: "15:00:00",
        semana: "50",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Sábado",
        carril: "Av. Kr. 13",
        sentido: "EW",
        desde: "Av. Cl. 26",
        hasta: "Av. Cl. 100",
        congestion: 38
    },

    // Av. 68 - NS - Diciembre 2021
    {
        fecha: "2021-12-15",
        hora: "08:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. 68",
        sentido: "NS",
        desde: "Av. Kr. 7",
        hasta: "Av. Kr. 15",
        congestion: 67
    },
    {
        fecha: "2021-12-15",
        hora: "17:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. 68",
        sentido: "NS",
        desde: "Av. Kr. 7",
        hasta: "Av. Kr. 15",
        congestion: 84
    },
    {
        fecha: "2021-12-15",
        hora: "18:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. 68",
        sentido: "NS",
        desde: "Av. Kr. 7",
        hasta: "Av. Kr. 15",
        congestion: 79
    },

    // Av. 68 - NS - Diciembre 2021 - Sábado
    {
        fecha: "2021-12-18",
        hora: "12:00:00",
        semana: "50",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Sábado",
        carril: "Av. 68",
        sentido: "NS",
        desde: "Av. Kr. 7",
        hasta: "Av. Kr. 15",
        congestion: 35
    },

    // Av. 19 - EW - Diciembre 2021
    {
        fecha: "2021-12-15",
        hora: "08:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. 19",
        sentido: "EW",
        desde: "Av. Kr. 13",
        hasta: "Av. Caracas",
        congestion: 73
    },
    {
        fecha: "2021-12-15",
        hora: "17:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. 19",
        sentido: "EW",
        desde: "Av. Kr. 13",
        hasta: "Av. Caracas",
        congestion: 89
    },
    {
        fecha: "2021-12-15",
        hora: "18:00:00",
        semana: "50",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. 19",
        sentido: "EW",
        desde: "Av. Kr. 13",
        hasta: "Av. Caracas",
        congestion: 82
    },

    // Av. 19 - EW - Diciembre 2021 - Sábado
    {
        fecha: "2021-12-18",
        hora: "13:00:00",
        semana: "50",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Sábado",
        carril: "Av. 19",
        sentido: "EW",
        desde: "Av. Kr. 13",
        hasta: "Av. Caracas",
        congestion: 41
    },

    // Más datos para completar - Diciembre 20-31, 2021
    {
        fecha: "2021-12-20",
        hora: "08:00:00",
        semana: "51",
        dia: "Lunes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 81
    },
    {
        fecha: "2021-12-20",
        hora: "17:00:00",
        semana: "51",
        dia: "Lunes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 93
    },
    {
        fecha: "2021-12-21",
        hora: "08:00:00",
        semana: "51",
        dia: "Martes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 79
    },
    {
        fecha: "2021-12-21",
        hora: "17:00:00",
        semana: "51",
        dia: "Martes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 87
    },
    {
        fecha: "2021-12-22",
        hora: "08:00:00",
        semana: "51",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 76
    },
    {
        fecha: "2021-12-22",
        hora: "17:00:00",
        semana: "51",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 91
    },
    {
        fecha: "2021-12-23",
        hora: "08:00:00",
        semana: "51",
        dia: "Jueves",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 83
    },
    {
        fecha: "2021-12-23",
        hora: "17:00:00",
        semana: "51",
        dia: "Jueves",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 89
    },
    {
        fecha: "2021-12-24",
        hora: "10:00:00",
        semana: "51",
        dia: "Viernes",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 28
    },
    {
        fecha: "2021-12-24",
        hora: "14:00:00",
        semana: "51",
        dia: "Viernes",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 35
    },
    {
        fecha: "2021-12-25",
        hora: "12:00:00",
        semana: "51",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 22
    },
    {
        fecha: "2021-12-25",
        hora: "16:00:00",
        semana: "51",
        dia: "Sábado",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 29
    },
    {
        fecha: "2021-12-26",
        hora: "11:00:00",
        semana: "52",
        dia: "Domingo",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 26
    },
    {
        fecha: "2021-12-26",
        hora: "15:00:00",
        semana: "52",
        dia: "Domingo",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 31
    },
    {
        fecha: "2021-12-27",
        hora: "08:00:00",
        semana: "52",
        dia: "Lunes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 77
    },
    {
        fecha: "2021-12-27",
        hora: "17:00:00",
        semana: "52",
        dia: "Lunes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 85
    },
    {
        fecha: "2021-12-28",
        hora: "08:00:00",
        semana: "52",
        dia: "Martes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 80
    },
    {
        fecha: "2021-12-28",
        hora: "17:00:00",
        semana: "52",
        dia: "Martes",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 88
    },
    {
        fecha: "2021-12-29",
        hora: "08:00:00",
        semana: "52",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 75
    },
    {
        fecha: "2021-12-29",
        hora: "17:00:00",
        semana: "52",
        dia: "Miércoles",
        mes: "Diciembre",
        tipoDia: "Hábil",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 86
    },
    {
        fecha: "2021-12-30",
        hora: "10:00:00",
        semana: "52",
        dia: "Jueves",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 33
    },
    {
        fecha: "2021-12-30",
        hora: "14:00:00",
        semana: "52",
        dia: "Jueves",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 39
    },
    {
        fecha: "2021-12-31",
        hora: "10:00:00",
        semana: "52",
        dia: "Viernes",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 27
    },
    {
        fecha: "2021-12-31",
        hora: "16:00:00",
        semana: "52",
        dia: "Viernes",
        mes: "Diciembre",
        tipoDia: "Festivo",
        carril: "Av. Boyacá",
        sentido: "NS",
        desde: "Av. Cl. 80",
        hasta: "Av. Primera de Mayo",
        congestion: 34
    }
];
